// closed_groups.cpp  (v2, scalable to N = 10..11)
//
// Enumerates, up to conjugacy, all subgroups of S_N that are realizable as the
// full automorphism group of an edge-weighted complete graph K_N (= symmetry
// groups of N-spin systems with scalar couplings). By the Galois correspondence
// these are exactly the 2^-closed groups (Wielandt closure w.r.t. unordered
// pairs): G is realizable iff G equals the automorphism group of its own orbit
// colouring of the edges.
//
// Method (sequential symmetrization as a provably complete BFS):
//   * a colouring is stored as a restricted-growth string over the E = N(N-1)/2
//     edges, edge order = column-by-column upper triangle (J12 J13 J23 J14 ...),
//     the same convention as materials/8Spins.txt; the edge indexing, RGS
//     encoding and coarsening step are shared with the MPI enumerator via
//     spin_graph.h, and the canonical form / |Aut| via canon_ir.h;
//   * one step: coarsen a colouring so that a permutation sigma becomes an
//     automorphism (union-find merge of colour classes along sigma-orbits);
//     the classes of the result are the edge orbits of <Aut-so-far, sigma>;
//   * BFS from the discrete colouring (all edges distinct, trivial group).
// Completeness: every subgroup of S_N is generated by <= max(2, floor(N/2))
// elements (McIver--Neumann 1987), so floor(N/2) productive rounds exhaust all
// closed groups; the BFS simply runs until no new colouring appears.
//
// v2 scalability changes (needed for N >= 10, where N! = 3.6M+):
//   1. Round 1 uses ONE candidate permutation per cycle type (partition of N):
//      the canonical class of coarsen(discrete, sigma) depends only on the
//      conjugacy class of sigma, because any relabelling maps the discrete
//      colouring to an equivalent one. p(10) = 42 candidates instead of 10!-1.
//   2. Canonical form (lex-min RGS over all vertex orderings) and |Aut| are
//      computed by a nauty-style individualization-refinement canonicalizer
//      (canon_ir.h): colour refinement to an equitable partition, then a
//      refinement-guided search whose automorphism generators prune the
//      lex-min ordering walk by orbit, and Schreier-Sims for |Aut| with no
//      element enumeration.  Byte-identical output to the earlier
//      prefix-pruned search (verified over N=3..13) but 100-20000x faster on
//      the highly symmetric colourings that were its worst case; the S_N
//      histogram walk that needed a special shortcut is gone.  (Wall-clock of
//      the full enumeration is dominated by the coarsen+hash of the raw
//      colourings, not by canonization, so the end-to-end gain is modest; the
//      win is in removing the N!-walk pathologies as N grows.)
//   3. Raw colourings are deduplicated by hashing BEFORE canonization, and
//      both the sweep (over frontier entries) and the canonization (over
//      unique raws) are OpenMP-parallel.
//   (Double-coset reduction A\S_N/A of the candidate sigmas was tested and
//    found not to pay here: marking a coset costs more than coarsen+hash.)
//
// Output per N: the number of closed subgroup classes, the histogram of group
// orders, and (with VERBOSE=1) the canonical colourings in 8Spins.txt format.
//
// Build:  g++ -O3 -march=native -fopenmp -std=c++17 -o closed_groups closed_groups.cpp
// Run:    ./closed_groups [Nmin [Nmax]]            (default 3..9)
//         OMP_NUM_THREADS=96 ./closed_groups 10 10
//         VERBOSE=1 ./closed_groups 10 10 > catalog_N10.txt
// Known values (N=3..12): 3, 8, 11, 27, 36, 90, 131, 282, 394, 948.
// Timings: N=10 ~2 min on 4 cores; N=11 ~3.5 min and N=12 ~101 min on 48
// cores (2x Xeon Gold 6542Y, OMP_PLACES=cores OMP_PROC_BIND=close,
// numactl --interleave=all).
// Memory: a few GB up to N=12 (raw-dedup hash sets).
// TRACE=1 additionally prints, for every round >= 4, each newly found
// canonical colouring with its group order (identifies late stragglers).

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include <map>
#include <unordered_set>
#include <algorithm>
#include <numeric>
#include <chrono>
#include "spin_graph.h"     // N, E, eidxA, edgeV, now, buildEdges, rgsOf, coarsen, genPartitions
#include "canon_ir.h"
#ifdef _OPENMP
#include <omp.h>
#endif

using namespace std;

// canonical form: lexicographic minimum over all vertex orderings v of the
// RGS string read column by column ( c(v_i,v_j), j = 1..N-1, i < j ).
// Computed by the nauty-style individualization-refinement canonicalizer
// (canon_ir.h): colour refinement gives an equitable partition, the
// automorphism generators found during the refinement search prune the
// lex-min ordering walk by orbit, so highly symmetric colourings - the worst
// case for the old prefix search - are canonicalized 100-20000x faster while
// the output is byte-identical to the old lex-min (verified over N=3..13).
static string canon(const string& c)
{
    return canir::canonize(c, N, true);
}

// |Aut(c)| via the same canonicalizer (Schreier-Sims from the generators; no
// element enumeration, so S_N and other large groups are handled instantly).
static long long autOrder(const string& c)
{
    canir::CanonIR ir; ir.init(c, N); ir.run();
    return ir.autOrder();
}

int main(int argc, char** argv)
{
    int Nmin = 3, Nmax = 9;
    if (argc > 1) Nmin = Nmax = atoi(argv[1]);
    if (argc > 2) Nmax = atoi(argv[2]);
    bool verbose = getenv("VERBOSE") != NULL;

    for (N = Nmin; N <= Nmax; N++)
    {
        double t0 = now();
        buildEdges();

        int lab0[128]; for (int e = 0; e < E; e++) lab0[e] = e;
        string discrete = rgsOf(lab0);

        unordered_set<string> seen{ discrete }, rawSeen;
        vector<string> frontier;
        int rounds = 0;

        // ---- round 1: one candidate permutation per cycle type ----
        {
            rounds = 1;
            vector<vector<int>> parts; vector<int> tmp;
            genPartitions(N, N, tmp, parts);
            vector<string> raws;
            for (auto& pt : parts)
            {
                bool ident = true;
                for (int L : pt) if (L > 1) { ident = false; break; }
                if (ident) continue;
                int sig[16]; int o = 0;
                for (int L : pt) { for (int k = 0; k < L; k++) sig[o + k] = o + (k + 1) % L; o += L; }
                string r = coarsen(discrete, sig);
                if (rawSeen.insert(r).second) raws.push_back(r);
            }
            vector<string> cans(raws.size());
            #pragma omp parallel for schedule(dynamic)
            for (long long i = 0; i < (long long)raws.size(); i++)
                cans[(size_t)i] = canon(raws[(size_t)i]);
            for (const string& cc : cans)
                if (seen.insert(cc).second) frontier.push_back(cc);
            fprintf(stderr, "N=%d round 1: candidates %zu (cycle types), new %zu, total %zu (%.1fs)\n",
                    N, raws.size(), frontier.size(), seen.size(), now() - t0);
        }

        // ---- rounds >= 2: full sweep from every frontier entry ----
        while (!frontier.empty())
        {
            rounds++;
            double tr = now();
            unordered_set<string> cand;
            #pragma omp parallel
            {
                unordered_set<string> local;
                #pragma omp for schedule(dynamic)
                for (long long fi = 0; fi < (long long)frontier.size(); fi++)
                {
                    const string& c = frontier[(size_t)fi];
                    int sig[16]; for (int i = 0; i < N; i++) sig[i] = i;
                    while (next_permutation(sig, sig + N))
                        local.insert(coarsen(c, sig));
                    if (local.size() > 4000000)
                    {
                        #pragma omp critical
                        cand.insert(local.begin(), local.end());
                        local.clear();
                    }
                }
                #pragma omp critical
                cand.insert(local.begin(), local.end());
            }
            vector<string> raws;
            for (const string& r : cand)
                if (rawSeen.insert(r).second) raws.push_back(r);
            cand.clear();

            vector<string> cans(raws.size());
            #pragma omp parallel for schedule(dynamic)
            for (long long i = 0; i < (long long)raws.size(); i++)
                cans[(size_t)i] = canon(raws[(size_t)i]);

            vector<string> next;
            for (const string& cc : cans)
                if (seen.insert(cc).second) next.push_back(cc);
            fprintf(stderr, "N=%d round %d: frontier %zu, raw %zu, new %zu, total %zu (%.1fs)\n",
                    N, rounds, frontier.size(), raws.size(), next.size(), seen.size(), now() - tr);
            if (getenv("TRACE") && rounds >= 4)
                for (const string& cc : next)
                {
                    fprintf(stderr, "TRACE round %d order %lld:", rounds, autOrder(cc));
                    for (int e = 0; e < E; e++) fprintf(stderr, " %d", (int)cc[(size_t)e]);
                    fprintf(stderr, "\n");
                }
            frontier.swap(next);
        }

        // ---- order histogram ----
        vector<string> all(seen.begin(), seen.end());
        vector<long long> ords(all.size());
        #pragma omp parallel for schedule(dynamic)
        for (long long i = 0; i < (long long)all.size(); i++)
            ords[(size_t)i] = autOrder(all[(size_t)i]);
        map<long long, vector<const string*>> byOrder;
        for (size_t i = 0; i < all.size(); i++) byOrder[ords[i]].push_back(&all[i]);

        printf("N=%d: closed subgroup classes = %zu (productive rounds: %d, %.1fs)\n",
               N, seen.size(), rounds - 1, now() - t0);
        printf("  orders:");
        for (auto& kv : byOrder) printf(" %lld(x%zu)", kv.first, kv.second.size());
        printf("\n");
        if (verbose)
            for (auto& kv : byOrder)
            {
                printf("--- order %lld (x%zu) ---\n", kv.first, kv.second.size());
                for (const string* c : kv.second)
                {
                    for (int e = 0; e < E; e++) printf("%d ", (int)(*c)[(size_t)e]);
                    printf("\n");
                }
            }
        fflush(stdout);
    }
    return 0;
}
